// WaveSentinel Simulation Data Engine
// Standardized detection data model and mission dataset for DEMO / SIMULATION MODE

export const INITIAL_DETECTIONS = [
    {
        mission_id: 'WS-2026-001',
        frame_id: 'WS_001284',
        timestamp: '11:37:42',
        class: 'Shipwreck',
        confidence: 87,
        risk: 'HIGH',
        depth: '42.3 m',
        latitude: '20.4521° N',
        longitude: '85.1294° E',
        position_source: 'simulated',
        telemetry_source: 'simulation',
        heave: '+0.18 m',
        pitch: '+2.4°',
        roll: '-1.1°',
        motion_correction_state: 'metadata_only',
        input_quality: 'good',
        model_version: 'Phase-D Robust-V2-HN',
        review_status: 'pending', // 'pending' | 'confirmed' | 'dismissed' | 'flagged'
        operator_notes: 'Large vessel hull lying on rocky shelf.',
        color: 'text-red-400 border-red-500 bg-red-500/10'
    },
    {
        mission_id: 'WS-2026-001',
        frame_id: 'WS_001281',
        timestamp: '11:34:10',
        class: 'Pipe',
        confidence: 94,
        risk: 'MEDIUM',
        depth: '40.8 m',
        latitude: '20.4518° N',
        longitude: '85.1288° E',
        position_source: 'simulated',
        telemetry_source: 'simulation',
        heave: '+0.17 m',
        pitch: '+2.3°',
        roll: '-1.0°',
        motion_correction_state: 'metadata_only',
        input_quality: 'good',
        model_version: 'Phase-D Robust-V2-HN',
        review_status: 'confirmed',
        operator_notes: 'Subsea pipeline segment exposed.',
        color: 'text-amber-400 border-amber-400 bg-amber-500/10'
    },
    {
        mission_id: 'WS-2026-001',
        frame_id: 'WS_001275',
        timestamp: '11:29:05',
        class: 'Mine',
        confidence: 98,
        risk: 'CRITICAL',
        depth: '45.1 m',
        latitude: '20.4490° N',
        longitude: '85.1250° E',
        position_source: 'simulated',
        telemetry_source: 'simulation',
        heave: '+0.16 m',
        pitch: '+2.3°',
        roll: '-0.9°',
        motion_correction_state: 'metadata_only',
        input_quality: 'good',
        model_version: 'Phase-D Robust-V2-HN',
        review_status: 'pending',
        operator_notes: 'Legacy naval ordnance contact flag. Recommend EOD notification.',
        color: 'text-red-500 border-red-600 bg-red-600/10'
    },
    {
        mission_id: 'WS-2026-001',
        frame_id: 'WS_001264',
        timestamp: '11:18:22',
        class: 'Ghost Net',
        confidence: 69,
        risk: 'HIGH',
        depth: '38.5 m',
        latitude: '20.4430° N',
        longitude: '85.1210° E',
        position_source: 'simulated',
        telemetry_source: 'simulation',
        heave: '+0.19 m',
        pitch: '+2.5°',
        roll: '-1.2°',
        motion_correction_state: 'metadata_only',
        input_quality: 'good',
        model_version: 'Phase-D Robust-V2-HN',
        review_status: 'pending',
        operator_notes: 'Abandoned gillnet caught in coral spur.',
        color: 'text-purple-400 border-purple-400 bg-purple-500/10'
    },
    {
        mission_id: 'WS-2026-001',
        frame_id: 'WS_001250',
        timestamp: '10:52:14',
        class: 'Shipwreck',
        confidence: 91,
        risk: 'HIGH',
        depth: '48.0 m',
        latitude: '20.4380° N',
        longitude: '85.1180° E',
        position_source: 'simulated',
        telemetry_source: 'simulation',
        heave: '+0.15 m',
        pitch: '+2.2°',
        roll: '-0.8°',
        motion_correction_state: 'metadata_only',
        input_quality: 'good',
        model_version: 'Phase-D Robust-V2-HN',
        review_status: 'confirmed',
        operator_notes: 'Wooden vessel frame debris field.',
        color: 'text-red-400 border-red-500 bg-red-500/10'
    },
    {
        mission_id: 'WS-2026-001',
        frame_id: 'WS_001242',
        timestamp: '10:40:50',
        class: 'Pipe',
        confidence: 96,
        risk: 'LOW',
        depth: '36.2 m',
        latitude: '20.4320° N',
        longitude: '85.1120° E',
        position_source: 'simulated',
        telemetry_source: 'simulation',
        heave: '+0.14 m',
        pitch: '+2.1°',
        roll: '-0.7°',
        motion_correction_state: 'metadata_only',
        input_quality: 'good',
        model_version: 'Phase-D Robust-V2-HN',
        review_status: 'confirmed',
        operator_notes: 'Buried utility conduit line.',
        color: 'text-emerald-400 border-emerald-400 bg-emerald-500/10'
    },
    {
        mission_id: 'WS-2026-001',
        frame_id: 'WS_001235',
        timestamp: '10:28:15',
        class: 'Ghost Net',
        confidence: 74,
        risk: 'HIGH',
        depth: '41.0 m',
        latitude: '20.4290° N',
        longitude: '85.1090° E',
        position_source: 'simulated',
        telemetry_source: 'simulation',
        heave: '+0.18 m',
        pitch: '+2.4°',
        roll: '-1.1°',
        motion_correction_state: 'metadata_only',
        input_quality: 'good',
        model_version: 'Phase-D Robust-V2-HN',
        review_status: 'pending',
        operator_notes: 'Submerged monofilament mesh requiring recovery.',
        color: 'text-purple-400 border-purple-400 bg-purple-500/10'
    },
    {
        mission_id: 'WS-2026-001',
        frame_id: 'WS_001220',
        timestamp: '10:15:00',
        class: 'Mine',
        confidence: 89,
        risk: 'CRITICAL',
        depth: '44.5 m',
        latitude: '20.4210° N',
        longitude: '85.1020° E',
        position_source: 'simulated',
        telemetry_source: 'simulation',
        heave: '+0.20 m',
        pitch: '+2.6°',
        roll: '-1.3°',
        motion_correction_state: 'metadata_only',
        input_quality: 'good',
        model_version: 'Phase-D Robust-V2-HN',
        review_status: 'pending',
        operator_notes: 'Spherical metal contact object on seabed.',
        color: 'text-red-500 border-red-600 bg-red-600/10'
    }
];

export const INITIAL_MISSION_STATE = {
    missionId: 'WS-2026-001',
    status: 'ACTIVE', // ACTIVE, PAUSED, ENDED
    surveyArea: 'Bay Sector 04',
    surveyLine: 'L-04',
    operationalMode: 'SIMULATION',
    framesProcessed: 1284,
    framesTotal: 2000,
    sssRange: 100, // meters
    simulatedSwath: 200, // meters
    frameRate: 8.4, // FPS
    vesselSpeed: 4.2, // knots
    heading: 142, // degrees
    depth: 42.3, // meters
    detectionsCount: 347,
    highRiskCount: 42,
    avgLatencyMs: 42
};

export const INITIAL_SETTINGS = {
    simulationMode: true,
    syntheticSssStream: true,
    syntheticTelemetry: true,
    simulatedGeolocation: true,
    motionMetadata: true,
    confidenceCutoff: 70,
    iouThreshold: 45,
    gpuDevice: 'RTX 4050 (Device 0)'
};
